[package]
name = "aac"
version = "0.2.0"
edition = "2021"
# MSRV
rust-version = "1.81.0"
license = "FDK-AAC"
description = "AAC-ELD decoder: a Third-Party Modified Version of the Fraunhofer FDK AAC Codec Library for Android"
readme = "README.md"
keywords = ["aac", "aac-eld", "audio", "codec", "decoder"]

[lib]
crate-type = ["lib"]

[dependencies]
arrayvec = "0.7.6"
bitflags = "2.5.0"
itertools = "0.10.5"
num-complex = "0.4.6"
paste = "1.0.15"
zerocopy = "0.8.20"
